### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by emorling** [kvendrik/intercom-react#10]
I get this issue using this plugin. Any ideas?

**Comment by kvendrik** [comment]
Hey @emorling,

Yeah so the library currently [imports `babel-polyfill`](https://github.com/kvendrik/intercom-react/blob/94fe36a0518ed051af5bb8bca2fa8b489fde29ae/webpack.config.js#L15) as well which is not good don't have a solution for this yet, its part of the open problems with the build which is why this project is still WIP. I'm very open to a PR that would help fix this of course.

**Comment by maccuaa** [comment]
@kvendrik just installed this package and still getting this error.  I noticed in NPM that the last publish of this package was 6 months ago, can you publish a new version with this fix?

**Comment by kvendrik** [comment]
@maccuaa the issue was fixed in #11. The package is however still WIP and not ready for use yet. Feel free to contribute to the [final steps needed to get the alpha out.](https://github.com/kvendrik/intercom-react/pull/14) In the meantime I recommend using a package like [`react-intercom`](https://github.com/nhagen/react-intercom) if that works for your use-case (it mounts Intercom to the global scope).

**Comment by maccuaa** [comment]
@kvendrik any items in particular? It looks like there are already tests for basic Intercom functionality like user data and location change.

**Comment by kvendrik** [comment]
@maccuaa the last items are in the description of [this PR](https://github.com/kvendrik/intercom-react/pull/15).
